// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type DateRangeInput struct {
	Start time.Time `json:"start"`
	End   time.Time `json:"end"`
}

type DispenseActionInput struct {
	EventID      *string        `json:"eventId,omitempty"`
	PatientID    string         `json:"patientId"`
	ScheduleID   string         `json:"scheduleId"`
	DueAtIso     time.Time      `json:"dueAtISO"`
	ActedAtIso   *time.Time     `json:"actedAtISO,omitempty"`
	Status       DispenseStatus `json:"status"`
	ActionSource *string        `json:"actionSource,omitempty"`
}

type DispenseEvent struct {
	ID           string         `json:"id"`
	PatientID    string         `json:"patientId"`
	ScheduleID   string         `json:"scheduleId"`
	DueAtIso     time.Time      `json:"dueAtISO"`
	ActedAtIso   *time.Time     `json:"actedAtISO,omitempty"`
	Status       DispenseStatus `json:"status"`
	ActionSource *string        `json:"actionSource,omitempty"`
	CreatedAt    time.Time      `json:"createdAt"`
}

type DueMedication struct {
	Medication *Medication `json:"medication"`
	Qty        int         `json:"qty"`
	SiloSlot   *int        `json:"siloSlot,omitempty"`
}

type DueSchedule struct {
	Schedule    *Schedule        `json:"schedule"`
	DueAtIso    time.Time        `json:"dueAtISO"`
	Medications []*DueMedication `json:"medications"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Medication struct {
	ID                string    `json:"id"`
	PatientID         string    `json:"patientId"`
	Name              string    `json:"name"`
	Color             *string   `json:"color,omitempty"`
	StockCount        int       `json:"stockCount"`
	LowStockThreshold int       `json:"lowStockThreshold"`
	CartridgeIndex    *int      `json:"cartridgeIndex,omitempty"`
	MaxDailyDose      int       `json:"maxDailyDose"`
	CreatedAt         time.Time `json:"createdAt"`
	UpdatedAt         time.Time `json:"updatedAt"`
}

type MedicationInput struct {
	ID                *string `json:"id,omitempty"`
	PatientID         string  `json:"patientId"`
	Name              string  `json:"name"`
	Color             *string `json:"color,omitempty"`
	StockCount        *int    `json:"stockCount,omitempty"`
	LowStockThreshold *int    `json:"lowStockThreshold,omitempty"`
	CartridgeIndex    *int    `json:"cartridgeIndex,omitempty"`
	MaxDailyDose      *int    `json:"maxDailyDose,omitempty"`
}

type Mutation struct {
}

type Patient struct {
	ID                     string           `json:"id"`
	UserID                 *string          `json:"userId,omitempty"`
	FirstName              string           `json:"firstName"`
	LastName               string           `json:"lastName"`
	Timezone               string           `json:"timezone"`
	CreatedAt              time.Time        `json:"createdAt"`
	UpdatedAt              time.Time        `json:"updatedAt"`
	Medications            []*Medication    `json:"medications"`
	Schedules              []*Schedule      `json:"schedules"`
	UpcomingDispenseEvents []*DispenseEvent `json:"upcomingDispenseEvents"`
}

type PatientInput struct {
	UserID    *string `json:"userId,omitempty"`
	FirstName string  `json:"firstName"`
	LastName  string  `json:"lastName"`
	Timezone  string  `json:"timezone"`
}

type Query struct {
}

type Schedule struct {
	ID             string          `json:"id"`
	PatientID      string          `json:"patientId"`
	Title          string          `json:"title"`
	Timezone       string          `json:"timezone"`
	Rrule          string          `json:"rrule"`
	StartDateIso   time.Time       `json:"startDateISO"`
	EndDateIso     *time.Time      `json:"endDateISO,omitempty"`
	LockoutMinutes int             `json:"lockoutMinutes"`
	Status         ScheduleStatus  `json:"status"`
	Items          []*ScheduleItem `json:"items"`
	CreatedAt      time.Time       `json:"createdAt"`
	UpdatedAt      time.Time       `json:"updatedAt"`
}

type ScheduleInput struct {
	ID             *string              `json:"id,omitempty"`
	PatientID      string               `json:"patientId"`
	Title          string               `json:"title"`
	Timezone       string               `json:"timezone"`
	Rrule          string               `json:"rrule"`
	StartDateIso   time.Time            `json:"startDateISO"`
	EndDateIso     *time.Time           `json:"endDateISO,omitempty"`
	LockoutMinutes int                  `json:"lockoutMinutes"`
	Status         *ScheduleStatus      `json:"status,omitempty"`
	Items          []*ScheduleItemInput `json:"items"`
}

type ScheduleItem struct {
	ID         string      `json:"id"`
	ScheduleID string      `json:"scheduleId"`
	Medication *Medication `json:"medication"`
	Qty        int         `json:"qty"`
}

type ScheduleItemInput struct {
	MedicationID string `json:"medicationId"`
	Qty          int    `json:"qty"`
}

type User struct {
	ID        string     `json:"id"`
	Email     string     `json:"email"`
	FullName  string     `json:"fullName"`
	Phone     *string    `json:"phone,omitempty"`
	Timezone  string     `json:"timezone"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	Patients  []*Patient `json:"patients"`
}

type UserInput struct {
	ID       *string `json:"id,omitempty"`
	Email    string  `json:"email"`
	FullName string  `json:"fullName"`
	Phone    *string `json:"phone,omitempty"`
	Timezone string  `json:"timezone"`
	Password *string `json:"password,omitempty"`
}

type DispenseStatus string

const (
	DispenseStatusPending DispenseStatus = "PENDING"
	DispenseStatusTaken   DispenseStatus = "TAKEN"
	DispenseStatusSkipped DispenseStatus = "SKIPPED"
	DispenseStatusFailed  DispenseStatus = "FAILED"
	DispenseStatusMissed  DispenseStatus = "MISSED"
)

var AllDispenseStatus = []DispenseStatus{
	DispenseStatusPending,
	DispenseStatusTaken,
	DispenseStatusSkipped,
	DispenseStatusFailed,
	DispenseStatusMissed,
}

func (e DispenseStatus) IsValid() bool {
	switch e {
	case DispenseStatusPending, DispenseStatusTaken, DispenseStatusSkipped, DispenseStatusFailed, DispenseStatusMissed:
		return true
	}
	return false
}

func (e DispenseStatus) String() string {
	return string(e)
}

func (e *DispenseStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DispenseStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DispenseStatus", str)
	}
	return nil
}

func (e DispenseStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DispenseStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DispenseStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ScheduleStatus string

const (
	ScheduleStatusActive   ScheduleStatus = "ACTIVE"
	ScheduleStatusPaused   ScheduleStatus = "PAUSED"
	ScheduleStatusArchived ScheduleStatus = "ARCHIVED"
)

var AllScheduleStatus = []ScheduleStatus{
	ScheduleStatusActive,
	ScheduleStatusPaused,
	ScheduleStatusArchived,
}

func (e ScheduleStatus) IsValid() bool {
	switch e {
	case ScheduleStatusActive, ScheduleStatusPaused, ScheduleStatusArchived:
		return true
	}
	return false
}

func (e ScheduleStatus) String() string {
	return string(e)
}

func (e *ScheduleStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ScheduleStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ScheduleStatus", str)
	}
	return nil
}

func (e ScheduleStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ScheduleStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ScheduleStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
