// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: active_patient.sql

package db

import (
	"context"
)

const getActivePatient = `-- name: GetActivePatient :one
SELECT patient_id, updated_at
FROM active_patient
WHERE id = 1
`

type GetActivePatientRow struct {
	PatientID string `json:"patient_id"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) GetActivePatient(ctx context.Context) (GetActivePatientRow, error) {
	row := q.queryRow(ctx, q.getActivePatientStmt, getActivePatient)
	var i GetActivePatientRow
	err := row.Scan(&i.PatientID, &i.UpdatedAt)
	return i, err
}

const setActivePatient = `-- name: SetActivePatient :exec
INSERT INTO active_patient (id, patient_id, updated_at)
VALUES (1, ?, datetime('now'))
ON CONFLICT(id) DO UPDATE SET
  patient_id = excluded.patient_id,
  updated_at = datetime('now')
`

func (q *Queries) SetActivePatient(ctx context.Context, patientID string) error {
	_, err := q.exec(ctx, q.setActivePatientStmt, setActivePatient, patientID)
	return err
}
