// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.archiveScheduleStmt, err = db.PrepareContext(ctx, archiveSchedule); err != nil {
		return nil, fmt.Errorf("error preparing query ArchiveSchedule: %w", err)
	}
	if q.createDispenseEventStmt, err = db.PrepareContext(ctx, createDispenseEvent); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDispenseEvent: %w", err)
	}
	if q.createMedicationStmt, err = db.PrepareContext(ctx, createMedication); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMedication: %w", err)
	}
	if q.createPatientStmt, err = db.PrepareContext(ctx, createPatient); err != nil {
		return nil, fmt.Errorf("error preparing query CreatePatient: %w", err)
	}
	if q.createScheduleStmt, err = db.PrepareContext(ctx, createSchedule); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSchedule: %w", err)
	}
	if q.createScheduleItemStmt, err = db.PrepareContext(ctx, createScheduleItem); err != nil {
		return nil, fmt.Errorf("error preparing query CreateScheduleItem: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteMedicationStmt, err = db.PrepareContext(ctx, deleteMedication); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMedication: %w", err)
	}
	if q.deleteScheduleItemsByScheduleStmt, err = db.PrepareContext(ctx, deleteScheduleItemsBySchedule); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteScheduleItemsBySchedule: %w", err)
	}
	if q.getDispenseEventStmt, err = db.PrepareContext(ctx, getDispenseEvent); err != nil {
		return nil, fmt.Errorf("error preparing query GetDispenseEvent: %w", err)
	}
	if q.getMedicationStmt, err = db.PrepareContext(ctx, getMedication); err != nil {
		return nil, fmt.Errorf("error preparing query GetMedication: %w", err)
	}
	if q.getPatientStmt, err = db.PrepareContext(ctx, getPatient); err != nil {
		return nil, fmt.Errorf("error preparing query GetPatient: %w", err)
	}
	if q.getScheduleStmt, err = db.PrepareContext(ctx, getSchedule); err != nil {
		return nil, fmt.Errorf("error preparing query GetSchedule: %w", err)
	}
	if q.getUserStmt, err = db.PrepareContext(ctx, getUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetUser: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.listDispenseEventsByPatientStmt, err = db.PrepareContext(ctx, listDispenseEventsByPatient); err != nil {
		return nil, fmt.Errorf("error preparing query ListDispenseEventsByPatient: %w", err)
	}
	if q.listMedicationsByPatientStmt, err = db.PrepareContext(ctx, listMedicationsByPatient); err != nil {
		return nil, fmt.Errorf("error preparing query ListMedicationsByPatient: %w", err)
	}
	if q.listPatientsStmt, err = db.PrepareContext(ctx, listPatients); err != nil {
		return nil, fmt.Errorf("error preparing query ListPatients: %w", err)
	}
	if q.listPatientsByUserStmt, err = db.PrepareContext(ctx, listPatientsByUser); err != nil {
		return nil, fmt.Errorf("error preparing query ListPatientsByUser: %w", err)
	}
	if q.listScheduleItemsByScheduleStmt, err = db.PrepareContext(ctx, listScheduleItemsBySchedule); err != nil {
		return nil, fmt.Errorf("error preparing query ListScheduleItemsBySchedule: %w", err)
	}
	if q.listSchedulesByPatientStmt, err = db.PrepareContext(ctx, listSchedulesByPatient); err != nil {
		return nil, fmt.Errorf("error preparing query ListSchedulesByPatient: %w", err)
	}
	if q.listUsersStmt, err = db.PrepareContext(ctx, listUsers); err != nil {
		return nil, fmt.Errorf("error preparing query ListUsers: %w", err)
	}
	if q.updateDispenseEventStmt, err = db.PrepareContext(ctx, updateDispenseEvent); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateDispenseEvent: %w", err)
	}
	if q.updateMedicationStmt, err = db.PrepareContext(ctx, updateMedication); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMedication: %w", err)
	}
	if q.updatePatientStmt, err = db.PrepareContext(ctx, updatePatient); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePatient: %w", err)
	}
	if q.updateScheduleStmt, err = db.PrepareContext(ctx, updateSchedule); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSchedule: %w", err)
	}
	if q.updateUserStmt, err = db.PrepareContext(ctx, updateUser); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUser: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.archiveScheduleStmt != nil {
		if cerr := q.archiveScheduleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing archiveScheduleStmt: %w", cerr)
		}
	}
	if q.createDispenseEventStmt != nil {
		if cerr := q.createDispenseEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDispenseEventStmt: %w", cerr)
		}
	}
	if q.createMedicationStmt != nil {
		if cerr := q.createMedicationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMedicationStmt: %w", cerr)
		}
	}
	if q.createPatientStmt != nil {
		if cerr := q.createPatientStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createPatientStmt: %w", cerr)
		}
	}
	if q.createScheduleStmt != nil {
		if cerr := q.createScheduleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createScheduleStmt: %w", cerr)
		}
	}
	if q.createScheduleItemStmt != nil {
		if cerr := q.createScheduleItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createScheduleItemStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteMedicationStmt != nil {
		if cerr := q.deleteMedicationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMedicationStmt: %w", cerr)
		}
	}
	if q.deleteScheduleItemsByScheduleStmt != nil {
		if cerr := q.deleteScheduleItemsByScheduleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteScheduleItemsByScheduleStmt: %w", cerr)
		}
	}
	if q.getDispenseEventStmt != nil {
		if cerr := q.getDispenseEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDispenseEventStmt: %w", cerr)
		}
	}
	if q.getMedicationStmt != nil {
		if cerr := q.getMedicationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMedicationStmt: %w", cerr)
		}
	}
	if q.getPatientStmt != nil {
		if cerr := q.getPatientStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPatientStmt: %w", cerr)
		}
	}
	if q.getScheduleStmt != nil {
		if cerr := q.getScheduleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getScheduleStmt: %w", cerr)
		}
	}
	if q.getUserStmt != nil {
		if cerr := q.getUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.listDispenseEventsByPatientStmt != nil {
		if cerr := q.listDispenseEventsByPatientStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDispenseEventsByPatientStmt: %w", cerr)
		}
	}
	if q.listMedicationsByPatientStmt != nil {
		if cerr := q.listMedicationsByPatientStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMedicationsByPatientStmt: %w", cerr)
		}
	}
	if q.listPatientsStmt != nil {
		if cerr := q.listPatientsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPatientsStmt: %w", cerr)
		}
	}
	if q.listPatientsByUserStmt != nil {
		if cerr := q.listPatientsByUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPatientsByUserStmt: %w", cerr)
		}
	}
	if q.listScheduleItemsByScheduleStmt != nil {
		if cerr := q.listScheduleItemsByScheduleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listScheduleItemsByScheduleStmt: %w", cerr)
		}
	}
	if q.listSchedulesByPatientStmt != nil {
		if cerr := q.listSchedulesByPatientStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSchedulesByPatientStmt: %w", cerr)
		}
	}
	if q.listUsersStmt != nil {
		if cerr := q.listUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUsersStmt: %w", cerr)
		}
	}
	if q.updateDispenseEventStmt != nil {
		if cerr := q.updateDispenseEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateDispenseEventStmt: %w", cerr)
		}
	}
	if q.updateMedicationStmt != nil {
		if cerr := q.updateMedicationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMedicationStmt: %w", cerr)
		}
	}
	if q.updatePatientStmt != nil {
		if cerr := q.updatePatientStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePatientStmt: %w", cerr)
		}
	}
	if q.updateScheduleStmt != nil {
		if cerr := q.updateScheduleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateScheduleStmt: %w", cerr)
		}
	}
	if q.updateUserStmt != nil {
		if cerr := q.updateUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                DBTX
	tx                                *sql.Tx
	archiveScheduleStmt               *sql.Stmt
	createDispenseEventStmt           *sql.Stmt
	createMedicationStmt              *sql.Stmt
	createPatientStmt                 *sql.Stmt
	createScheduleStmt                *sql.Stmt
	createScheduleItemStmt            *sql.Stmt
	createUserStmt                    *sql.Stmt
	deleteMedicationStmt              *sql.Stmt
	deleteScheduleItemsByScheduleStmt *sql.Stmt
	getDispenseEventStmt              *sql.Stmt
	getMedicationStmt                 *sql.Stmt
	getPatientStmt                    *sql.Stmt
	getScheduleStmt                   *sql.Stmt
	getUserStmt                       *sql.Stmt
	getUserByEmailStmt                *sql.Stmt
	listDispenseEventsByPatientStmt   *sql.Stmt
	listMedicationsByPatientStmt      *sql.Stmt
	listPatientsStmt                  *sql.Stmt
	listPatientsByUserStmt            *sql.Stmt
	listScheduleItemsByScheduleStmt   *sql.Stmt
	listSchedulesByPatientStmt        *sql.Stmt
	listUsersStmt                     *sql.Stmt
	updateDispenseEventStmt           *sql.Stmt
	updateMedicationStmt              *sql.Stmt
	updatePatientStmt                 *sql.Stmt
	updateScheduleStmt                *sql.Stmt
	updateUserStmt                    *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                tx,
		tx:                                tx,
		archiveScheduleStmt:               q.archiveScheduleStmt,
		createDispenseEventStmt:           q.createDispenseEventStmt,
		createMedicationStmt:              q.createMedicationStmt,
		createPatientStmt:                 q.createPatientStmt,
		createScheduleStmt:                q.createScheduleStmt,
		createScheduleItemStmt:            q.createScheduleItemStmt,
		createUserStmt:                    q.createUserStmt,
		deleteMedicationStmt:              q.deleteMedicationStmt,
		deleteScheduleItemsByScheduleStmt: q.deleteScheduleItemsByScheduleStmt,
		getDispenseEventStmt:              q.getDispenseEventStmt,
		getMedicationStmt:                 q.getMedicationStmt,
		getPatientStmt:                    q.getPatientStmt,
		getScheduleStmt:                   q.getScheduleStmt,
		getUserStmt:                       q.getUserStmt,
		getUserByEmailStmt:                q.getUserByEmailStmt,
		listDispenseEventsByPatientStmt:   q.listDispenseEventsByPatientStmt,
		listMedicationsByPatientStmt:      q.listMedicationsByPatientStmt,
		listPatientsStmt:                  q.listPatientsStmt,
		listPatientsByUserStmt:            q.listPatientsByUserStmt,
		listScheduleItemsByScheduleStmt:   q.listScheduleItemsByScheduleStmt,
		listSchedulesByPatientStmt:        q.listSchedulesByPatientStmt,
		listUsersStmt:                     q.listUsersStmt,
		updateDispenseEventStmt:           q.updateDispenseEventStmt,
		updateMedicationStmt:              q.updateMedicationStmt,
		updatePatientStmt:                 q.updatePatientStmt,
		updateScheduleStmt:                q.updateScheduleStmt,
		updateUserStmt:                    q.updateUserStmt,
	}
}
