// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dispense_events.sql

package db

import (
	"context"
	"database/sql"
)

const createDispenseEvent = `-- name: CreateDispenseEvent :one
INSERT INTO dispense_events (
  id,
  patient_id,
  schedule_id,
  schedule_item_id,
  due_at_iso,
  acted_at_iso,
  status,
  action_source,
  notes,
  metadata
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING
  id,
  patient_id,
  schedule_id,
  schedule_item_id,
  due_at_iso,
  acted_at_iso,
  status,
  action_source,
  notes,
  metadata,
  created_at
`

type CreateDispenseEventParams struct {
	ID             string         `json:"id"`
	PatientID      string         `json:"patient_id"`
	ScheduleID     string         `json:"schedule_id"`
	ScheduleItemID sql.NullString `json:"schedule_item_id"`
	DueAtIso       string         `json:"due_at_iso"`
	ActedAtIso     sql.NullString `json:"acted_at_iso"`
	Status         string         `json:"status"`
	ActionSource   sql.NullString `json:"action_source"`
	Notes          sql.NullString `json:"notes"`
	Metadata       string         `json:"metadata"`
}

func (q *Queries) CreateDispenseEvent(ctx context.Context, arg CreateDispenseEventParams) (DispenseEvent, error) {
	row := q.queryRow(ctx, q.createDispenseEventStmt, createDispenseEvent,
		arg.ID,
		arg.PatientID,
		arg.ScheduleID,
		arg.ScheduleItemID,
		arg.DueAtIso,
		arg.ActedAtIso,
		arg.Status,
		arg.ActionSource,
		arg.Notes,
		arg.Metadata,
	)
	var i DispenseEvent
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.ScheduleID,
		&i.ScheduleItemID,
		&i.DueAtIso,
		&i.ActedAtIso,
		&i.Status,
		&i.ActionSource,
		&i.Notes,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getDispenseEvent = `-- name: GetDispenseEvent :one
SELECT
  id,
  patient_id,
  schedule_id,
  schedule_item_id,
  due_at_iso,
  acted_at_iso,
  status,
  action_source,
  notes,
  metadata,
  created_at
FROM dispense_events
WHERE id = ?
`

func (q *Queries) GetDispenseEvent(ctx context.Context, id string) (DispenseEvent, error) {
	row := q.queryRow(ctx, q.getDispenseEventStmt, getDispenseEvent, id)
	var i DispenseEvent
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.ScheduleID,
		&i.ScheduleItemID,
		&i.DueAtIso,
		&i.ActedAtIso,
		&i.Status,
		&i.ActionSource,
		&i.Notes,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listDispenseEventsByPatient = `-- name: ListDispenseEventsByPatient :many
SELECT
  id,
  patient_id,
  schedule_id,
  schedule_item_id,
  due_at_iso,
  acted_at_iso,
  status,
  action_source,
  notes,
  metadata,
  created_at
FROM dispense_events
WHERE patient_id = ?
  AND due_at_iso >= ?
  AND due_at_iso <= ?
ORDER BY due_at_iso DESC
`

type ListDispenseEventsByPatientParams struct {
	PatientID  string `json:"patient_id"`
	DueAtIso   string `json:"due_at_iso"`
	DueAtIso_2 string `json:"due_at_iso_2"`
}

func (q *Queries) ListDispenseEventsByPatient(ctx context.Context, arg ListDispenseEventsByPatientParams) ([]DispenseEvent, error) {
	rows, err := q.query(ctx, q.listDispenseEventsByPatientStmt, listDispenseEventsByPatient, arg.PatientID, arg.DueAtIso, arg.DueAtIso_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DispenseEvent{}
	for rows.Next() {
		var i DispenseEvent
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.ScheduleID,
			&i.ScheduleItemID,
			&i.DueAtIso,
			&i.ActedAtIso,
			&i.Status,
			&i.ActionSource,
			&i.Notes,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDispenseEvent = `-- name: UpdateDispenseEvent :one
UPDATE dispense_events
SET
  patient_id = ?,
  schedule_id = ?,
  schedule_item_id = ?,
  due_at_iso = ?,
  acted_at_iso = ?,
  status = ?,
  action_source = ?,
  notes = ?,
  metadata = ?
WHERE id = ?
RETURNING
  id,
  patient_id,
  schedule_id,
  schedule_item_id,
  due_at_iso,
  acted_at_iso,
  status,
  action_source,
  notes,
  metadata,
  created_at
`

type UpdateDispenseEventParams struct {
	PatientID      string         `json:"patient_id"`
	ScheduleID     string         `json:"schedule_id"`
	ScheduleItemID sql.NullString `json:"schedule_item_id"`
	DueAtIso       string         `json:"due_at_iso"`
	ActedAtIso     sql.NullString `json:"acted_at_iso"`
	Status         string         `json:"status"`
	ActionSource   sql.NullString `json:"action_source"`
	Notes          sql.NullString `json:"notes"`
	Metadata       string         `json:"metadata"`
	ID             string         `json:"id"`
}

func (q *Queries) UpdateDispenseEvent(ctx context.Context, arg UpdateDispenseEventParams) (DispenseEvent, error) {
	row := q.queryRow(ctx, q.updateDispenseEventStmt, updateDispenseEvent,
		arg.PatientID,
		arg.ScheduleID,
		arg.ScheduleItemID,
		arg.DueAtIso,
		arg.ActedAtIso,
		arg.Status,
		arg.ActionSource,
		arg.Notes,
		arg.Metadata,
		arg.ID,
	)
	var i DispenseEvent
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.ScheduleID,
		&i.ScheduleItemID,
		&i.DueAtIso,
		&i.ActedAtIso,
		&i.Status,
		&i.ActionSource,
		&i.Notes,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
