// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: medications.sql

package db

import (
	"context"
	"database/sql"
)

const createMedication = `-- name: CreateMedication :one
INSERT INTO medications (id, patient_id, name, color, stock_count, low_stock_threshold, cartridge_index, max_daily_dose)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, patient_id, name, color, stock_count, low_stock_threshold, cartridge_index, max_daily_dose, created_at, updated_at
`

type CreateMedicationParams struct {
	ID                string         `json:"id"`
	PatientID         string         `json:"patient_id"`
	Name              string         `json:"name"`
	Color             sql.NullString `json:"color"`
	StockCount        int64          `json:"stock_count"`
	LowStockThreshold int64          `json:"low_stock_threshold"`
	CartridgeIndex    sql.NullInt64  `json:"cartridge_index"`
	MaxDailyDose      int64          `json:"max_daily_dose"`
}

func (q *Queries) CreateMedication(ctx context.Context, arg CreateMedicationParams) (Medication, error) {
	row := q.queryRow(ctx, q.createMedicationStmt, createMedication,
		arg.ID,
		arg.PatientID,
		arg.Name,
		arg.Color,
		arg.StockCount,
		arg.LowStockThreshold,
		arg.CartridgeIndex,
		arg.MaxDailyDose,
	)
	var i Medication
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.Name,
		&i.Color,
		&i.StockCount,
		&i.LowStockThreshold,
		&i.CartridgeIndex,
		&i.MaxDailyDose,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMedication = `-- name: DeleteMedication :exec
DELETE FROM medications
WHERE id = ?
`

func (q *Queries) DeleteMedication(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteMedicationStmt, deleteMedication, id)
	return err
}

const getMedication = `-- name: GetMedication :one
SELECT id, patient_id, name, color, stock_count, low_stock_threshold, cartridge_index, max_daily_dose, created_at, updated_at FROM medications
WHERE id = ?
`

func (q *Queries) GetMedication(ctx context.Context, id string) (Medication, error) {
	row := q.queryRow(ctx, q.getMedicationStmt, getMedication, id)
	var i Medication
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.Name,
		&i.Color,
		&i.StockCount,
		&i.LowStockThreshold,
		&i.CartridgeIndex,
		&i.MaxDailyDose,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMedicationsByPatient = `-- name: ListMedicationsByPatient :many
SELECT id, patient_id, name, color, stock_count, low_stock_threshold, cartridge_index, max_daily_dose, created_at, updated_at FROM medications
WHERE patient_id = ?
ORDER BY name
`

func (q *Queries) ListMedicationsByPatient(ctx context.Context, patientID string) ([]Medication, error) {
	rows, err := q.query(ctx, q.listMedicationsByPatientStmt, listMedicationsByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medication{}
	for rows.Next() {
		var i Medication
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.Name,
			&i.Color,
			&i.StockCount,
			&i.LowStockThreshold,
			&i.CartridgeIndex,
			&i.MaxDailyDose,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMedication = `-- name: UpdateMedication :one
UPDATE medications
SET
  name = ?,
  color = ?,
  stock_count = ?,
  low_stock_threshold = ?,
  cartridge_index = ?,
  max_daily_dose = ?,
  updated_at = datetime('now')
WHERE id = ?
RETURNING id, patient_id, name, color, stock_count, low_stock_threshold, cartridge_index, max_daily_dose, created_at, updated_at
`

type UpdateMedicationParams struct {
	Name              string         `json:"name"`
	Color             sql.NullString `json:"color"`
	StockCount        int64          `json:"stock_count"`
	LowStockThreshold int64          `json:"low_stock_threshold"`
	CartridgeIndex    sql.NullInt64  `json:"cartridge_index"`
	MaxDailyDose      int64          `json:"max_daily_dose"`
	ID                string         `json:"id"`
}

func (q *Queries) UpdateMedication(ctx context.Context, arg UpdateMedicationParams) (Medication, error) {
	row := q.queryRow(ctx, q.updateMedicationStmt, updateMedication,
		arg.Name,
		arg.Color,
		arg.StockCount,
		arg.LowStockThreshold,
		arg.CartridgeIndex,
		arg.MaxDailyDose,
		arg.ID,
	)
	var i Medication
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.Name,
		&i.Color,
		&i.StockCount,
		&i.LowStockThreshold,
		&i.CartridgeIndex,
		&i.MaxDailyDose,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
