// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type DispenseEvent struct {
	ID           string         `json:"id"`
	PatientID    string         `json:"patient_id"`
	ScheduleID   string         `json:"schedule_id"`
	DueAtIso     string         `json:"due_at_iso"`
	ActedAtIso   sql.NullString `json:"acted_at_iso"`
	Status       string         `json:"status"`
	ActionSource sql.NullString `json:"action_source"`
	CreatedAt    string         `json:"created_at"`
}

type Medication struct {
	ID                string         `json:"id"`
	PatientID         string         `json:"patient_id"`
	Name              string         `json:"name"`
	Color             sql.NullString `json:"color"`
	StockCount        int64          `json:"stock_count"`
	LowStockThreshold int64          `json:"low_stock_threshold"`
	CartridgeIndex    sql.NullInt64  `json:"cartridge_index"`
	MaxDailyDose      int64          `json:"max_daily_dose"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
}

type Patient struct {
	ID        string         `json:"id"`
	UserID    sql.NullString `json:"user_id"`
	FirstName string         `json:"first_name"`
	LastName  string         `json:"last_name"`
	Timezone  string         `json:"timezone"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
}

type Schedule struct {
	ID             string         `json:"id"`
	PatientID      string         `json:"patient_id"`
	Title          string         `json:"title"`
	Timezone       string         `json:"timezone"`
	Rrule          string         `json:"rrule"`
	StartDateIso   string         `json:"start_date_iso"`
	EndDateIso     sql.NullString `json:"end_date_iso"`
	LockoutMinutes int64          `json:"lockout_minutes"`
	Status         string         `json:"status"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
}

type ScheduleItem struct {
	ID           string `json:"id"`
	ScheduleID   string `json:"schedule_id"`
	MedicationID string `json:"medication_id"`
	Qty          int64  `json:"qty"`
}

type User struct {
	ID           string         `json:"id"`
	Email        string         `json:"email"`
	FullName     string         `json:"full_name"`
	Phone        sql.NullString `json:"phone"`
	Timezone     string         `json:"timezone"`
	PasswordHash sql.NullString `json:"password_hash"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}
