// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_events.sql

package db

import (
	"context"
	"database/sql"
)

const createNotificationEvent = `-- name: CreateNotificationEvent :one
INSERT INTO notification_events (
  id,
  patient_id,
  schedule_id,
  user_id,
  due_at_iso,
  channel,
  destination,
  message,
  status,
  provider_message_id,
  error_message
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING
  id,
  patient_id,
  schedule_id,
  user_id,
  due_at_iso,
  channel,
  destination,
  message,
  status,
  provider_message_id,
  error_message,
  created_at
`

type CreateNotificationEventParams struct {
	ID                string         `json:"id"`
	PatientID         string         `json:"patient_id"`
	ScheduleID        string         `json:"schedule_id"`
	UserID            sql.NullString `json:"user_id"`
	DueAtIso          string         `json:"due_at_iso"`
	Channel           string         `json:"channel"`
	Destination       string         `json:"destination"`
	Message           string         `json:"message"`
	Status            string         `json:"status"`
	ProviderMessageID sql.NullString `json:"provider_message_id"`
	ErrorMessage      sql.NullString `json:"error_message"`
}

func (q *Queries) CreateNotificationEvent(ctx context.Context, arg CreateNotificationEventParams) (NotificationEvent, error) {
	row := q.queryRow(ctx, q.createNotificationEventStmt, createNotificationEvent,
		arg.ID,
		arg.PatientID,
		arg.ScheduleID,
		arg.UserID,
		arg.DueAtIso,
		arg.Channel,
		arg.Destination,
		arg.Message,
		arg.Status,
		arg.ProviderMessageID,
		arg.ErrorMessage,
	)
	var i NotificationEvent
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.ScheduleID,
		&i.UserID,
		&i.DueAtIso,
		&i.Channel,
		&i.Destination,
		&i.Message,
		&i.Status,
		&i.ProviderMessageID,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationEventByOccurrence = `-- name: GetNotificationEventByOccurrence :one
SELECT
  id,
  patient_id,
  schedule_id,
  user_id,
  due_at_iso,
  channel,
  destination,
  message,
  status,
  provider_message_id,
  error_message,
  created_at
FROM notification_events
WHERE patient_id = ?
  AND schedule_id = ?
  AND due_at_iso = ?
  AND channel = ?
`

type GetNotificationEventByOccurrenceParams struct {
	PatientID  string `json:"patient_id"`
	ScheduleID string `json:"schedule_id"`
	DueAtIso   string `json:"due_at_iso"`
	Channel    string `json:"channel"`
}

func (q *Queries) GetNotificationEventByOccurrence(ctx context.Context, arg GetNotificationEventByOccurrenceParams) (NotificationEvent, error) {
	row := q.queryRow(ctx, q.getNotificationEventByOccurrenceStmt, getNotificationEventByOccurrence,
		arg.PatientID,
		arg.ScheduleID,
		arg.DueAtIso,
		arg.Channel,
	)
	var i NotificationEvent
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.ScheduleID,
		&i.UserID,
		&i.DueAtIso,
		&i.Channel,
		&i.Destination,
		&i.Message,
		&i.Status,
		&i.ProviderMessageID,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationEventsByPatient = `-- name: ListNotificationEventsByPatient :many
SELECT
  id,
  patient_id,
  schedule_id,
  user_id,
  due_at_iso,
  channel,
  destination,
  message,
  status,
  provider_message_id,
  error_message,
  created_at
FROM notification_events
WHERE patient_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListNotificationEventsByPatient(ctx context.Context, patientID string) ([]NotificationEvent, error) {
	rows, err := q.query(ctx, q.listNotificationEventsByPatientStmt, listNotificationEventsByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationEvent{}
	for rows.Next() {
		var i NotificationEvent
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.ScheduleID,
			&i.UserID,
			&i.DueAtIso,
			&i.Channel,
			&i.Destination,
			&i.Message,
			&i.Status,
			&i.ProviderMessageID,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
