// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: patients.sql

package db

import (
	"context"
	"database/sql"
)

const createPatient = `-- name: CreatePatient :one
INSERT INTO patients (id, user_id, first_name, last_name, timezone)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, first_name, last_name, timezone, created_at, updated_at
`

type CreatePatientParams struct {
	ID        string         `json:"id"`
	UserID    sql.NullString `json:"user_id"`
	FirstName string         `json:"first_name"`
	LastName  string         `json:"last_name"`
	Timezone  string         `json:"timezone"`
}

func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error) {
	row := q.queryRow(ctx, q.createPatientStmt, createPatient,
		arg.ID,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.Timezone,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPatient = `-- name: GetPatient :one
SELECT id, user_id, first_name, last_name, timezone, created_at, updated_at
FROM patients
WHERE id = ?
`

func (q *Queries) GetPatient(ctx context.Context, id string) (Patient, error) {
	row := q.queryRow(ctx, q.getPatientStmt, getPatient, id)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPatients = `-- name: ListPatients :many
SELECT id, user_id, first_name, last_name, timezone, created_at, updated_at
FROM patients
ORDER BY created_at DESC
`

func (q *Queries) ListPatients(ctx context.Context) ([]Patient, error) {
	rows, err := q.query(ctx, q.listPatientsStmt, listPatients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Patient{}
	for rows.Next() {
		var i Patient
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatientsByUser = `-- name: ListPatientsByUser :many
SELECT id, user_id, first_name, last_name, timezone, created_at, updated_at
FROM patients
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListPatientsByUser(ctx context.Context, userID sql.NullString) ([]Patient, error) {
	rows, err := q.query(ctx, q.listPatientsByUserStmt, listPatientsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Patient{}
	for rows.Next() {
		var i Patient
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePatient = `-- name: UpdatePatient :one
UPDATE patients
SET
  user_id = ?,
  first_name = ?,
  last_name = ?,
  timezone = ?,
  updated_at = datetime('now')
WHERE id = ?
RETURNING id, user_id, first_name, last_name, timezone, created_at, updated_at
`

type UpdatePatientParams struct {
	UserID    sql.NullString `json:"user_id"`
	FirstName string         `json:"first_name"`
	LastName  string         `json:"last_name"`
	Timezone  string         `json:"timezone"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdatePatient(ctx context.Context, arg UpdatePatientParams) (Patient, error) {
	row := q.queryRow(ctx, q.updatePatientStmt, updatePatient,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.Timezone,
		arg.ID,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
