// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	ArchiveSchedule(ctx context.Context, id string) (Schedule, error)
	CreateDispenseEvent(ctx context.Context, arg CreateDispenseEventParams) (DispenseEvent, error)
	CreateMedication(ctx context.Context, arg CreateMedicationParams) (Medication, error)
	CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error)
	CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error)
	CreateScheduleItem(ctx context.Context, arg CreateScheduleItemParams) (ScheduleItem, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteMedication(ctx context.Context, id string) error
	DeleteScheduleItemsBySchedule(ctx context.Context, scheduleID string) error
	GetDispenseEvent(ctx context.Context, id string) (DispenseEvent, error)
	GetMedication(ctx context.Context, id string) (Medication, error)
	GetPatient(ctx context.Context, id string) (Patient, error)
	GetSchedule(ctx context.Context, id string) (Schedule, error)
	GetUser(ctx context.Context, id string) (GetUserRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListDispenseEventsByPatient(ctx context.Context, arg ListDispenseEventsByPatientParams) ([]DispenseEvent, error)
	ListMedicationsByPatient(ctx context.Context, patientID string) ([]Medication, error)
	ListPatients(ctx context.Context) ([]Patient, error)
	ListPatientsByUser(ctx context.Context, userID sql.NullString) ([]Patient, error)
	ListScheduleItemsBySchedule(ctx context.Context, scheduleID string) ([]ListScheduleItemsByScheduleRow, error)
	ListSchedulesByPatient(ctx context.Context, patientID string) ([]Schedule, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	UpdateDispenseEvent(ctx context.Context, arg UpdateDispenseEventParams) (DispenseEvent, error)
	UpdateMedication(ctx context.Context, arg UpdateMedicationParams) (Medication, error)
	UpdatePatient(ctx context.Context, arg UpdatePatientParams) (Patient, error)
	UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (Schedule, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
