// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  id,
  email,
  full_name,
  phone,
  timezone,
  password_hash
)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING
  id,
  email,
  full_name,
  phone,
  timezone,
  password_hash,
  created_at,
  updated_at
`

type CreateUserParams struct {
	ID           string         `json:"id"`
	Email        string         `json:"email"`
	FullName     string         `json:"full_name"`
	Phone        sql.NullString `json:"phone"`
	Timezone     string         `json:"timezone"`
	PasswordHash sql.NullString `json:"password_hash"`
}

type CreateUserRow struct {
	ID           string         `json:"id"`
	Email        string         `json:"email"`
	FullName     string         `json:"full_name"`
	Phone        sql.NullString `json:"phone"`
	Timezone     string         `json:"timezone"`
	PasswordHash sql.NullString `json:"password_hash"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser,
		arg.ID,
		arg.Email,
		arg.FullName,
		arg.Phone,
		arg.Timezone,
		arg.PasswordHash,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Phone,
		&i.Timezone,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT
  id,
  email,
  full_name,
  phone,
  timezone,
  created_at,
  updated_at
FROM users
WHERE id = ?
`

type GetUserRow struct {
	ID        string         `json:"id"`
	Email     string         `json:"email"`
	FullName  string         `json:"full_name"`
	Phone     sql.NullString `json:"phone"`
	Timezone  string         `json:"timezone"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
}

func (q *Queries) GetUser(ctx context.Context, id string) (GetUserRow, error) {
	row := q.queryRow(ctx, q.getUserStmt, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Phone,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
  id,
  email,
  full_name,
  phone,
  timezone,
  password_hash,
  created_at,
  updated_at
FROM users
WHERE email = ?
`

type GetUserByEmailRow struct {
	ID           string         `json:"id"`
	Email        string         `json:"email"`
	FullName     string         `json:"full_name"`
	Phone        sql.NullString `json:"phone"`
	Timezone     string         `json:"timezone"`
	PasswordHash sql.NullString `json:"password_hash"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Phone,
		&i.Timezone,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
  id,
  email,
  full_name,
  phone,
  timezone,
  created_at,
  updated_at
FROM users
ORDER BY created_at DESC
`

type ListUsersRow struct {
	ID        string         `json:"id"`
	Email     string         `json:"email"`
	FullName  string         `json:"full_name"`
	Phone     sql.NullString `json:"phone"`
	Timezone  string         `json:"timezone"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.query(ctx, q.listUsersStmt, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.Phone,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  email = ?,
  full_name = ?,
  phone = ?,
  timezone = ?,
  password_hash = ?,
  updated_at = datetime('now')
WHERE id = ?
RETURNING
  id,
  email,
  full_name,
  phone,
  timezone,
  password_hash,
  created_at,
  updated_at
`

type UpdateUserParams struct {
	Email        string         `json:"email"`
	FullName     string         `json:"full_name"`
	Phone        sql.NullString `json:"phone"`
	Timezone     string         `json:"timezone"`
	PasswordHash sql.NullString `json:"password_hash"`
	ID           string         `json:"id"`
}

type UpdateUserRow struct {
	ID           string         `json:"id"`
	Email        string         `json:"email"`
	FullName     string         `json:"full_name"`
	Phone        sql.NullString `json:"phone"`
	Timezone     string         `json:"timezone"`
	PasswordHash sql.NullString `json:"password_hash"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.queryRow(ctx, q.updateUserStmt, updateUser,
		arg.Email,
		arg.FullName,
		arg.Phone,
		arg.Timezone,
		arg.PasswordHash,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Phone,
		&i.Timezone,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
